name: IAC
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
jobs:
 conviso-iac:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       API_KEY:  ${{secrets.CONVISO_API_KEY}}
       PROJECT_CODE: ${{secrets.CONVISO_PROJECT_KEY}}
       API_URL: ${{secrets.CONVISO_HOMOLOGA_URL}}
   steps:
   - uses: actions/checkout@v2
   - name: Run iac
     run: conviso iac run
